### ISSUE TITLE
RestQL Server is duplicating resources requests

### ISSUE THREAD

**Issue by ajukas** [B2W-BIT/restQL-server#17]
I'm using restQL to integrate my microservices and I've noticed in my logs that it is making two requests for each resource I invoke. 

I think because of this we are having performance problems when comparing to our old solution.

Is this an actual problem or a default behavior?

Thanks.

If you need more information I can share a compose file with a sample and its logs

*I'm using the latest version

**Comment by ricardoekm** [comment]
Hi @ajukas,
restQL has a built-in retry mechanism, if the request to the target endpoint fails. It'll retry once. 

Can you please confirm that the endpoint is returning HTTP 200?

If it's simple for you please share the artifacts. In the mean time we'll try to reproduce it here.

**Comment by ajukas** [comment]
Hello @ricardoekm, thanks for the reply. The endpoint is return 200.

I've created a repository with the artifacts. It's a simple docker-compose file with a node app and our restql image. 
Repository: https://github.com/ajukas/restQL-sample-app

To reproduce you can execute:
`
git clone https://github.com/ajukas/restQL-sample-app &&
cd restQL-sample-app/ &&
docker-compose up
`

Running this request
`
curl -H "Content-Type: text/plain" localhost:9000/run-query -d "from sample with id = 123"
`
I get the following response:
![sample-app-response](https://user-images.githubusercontent.com/1136238/37742638-38dff720-2d45-11e8-996a-861ebd778e5c.png)

**Comment by ricardoekm** [comment]
We were able to reproduce the issue. It seems a bug in the retry code. 

We'll fix it and release a new version.

**Comment by ricardoekm** [comment]
We've just uploaded the release: https://github.com/B2W-BIT/restQL-server/releases/tag/v2.3.2

Can you please give it a try?

**Comment by ajukas** [comment]
Thank you for your efficiency!!! It's working as expected! Soon we will start the performance tests again!

**Comment by sio-iago** [comment]
@ricardoekm I guess it's resolved, so I'm closing it.

**Comment by ricardoekm** [comment]
@ajukas if restQL as-is performance doesn't meet your requirements there're some tunings you can work on. The most resource intensive task is the query parsing. To optimize this you can use named queries or when using ad-hoc queries use the token "$paramName" in the query body and pass the paramName as query string. This will allow restQL to cache the parsing and optimize the request.

**Comment by ajukas** [comment]
@ricardoekm Thanks for the suggestion, we are using saved queries on our tests.
