### ISSUE TITLE
Docs: duplicated requirements

### ISSUE THREAD

**Issue by ArxdSilva** [B2W-BIT/restQL-server#4]
Hey guys! Was looking at your wiki and noticed that on section `Building From Source Code`, while listing the prerequisites you've listed twice the following items:
- Java 8
- MongoDB

Since by default [only collaborator's can contribute](https://help.github.com/articles/about-github-wikis/) to a project's wiki, I can't make a PR about It. Keep on the good work!

**Comment by jsanchesleao** [comment]
Hey, thank you for pointing that, so we could fix the doc.

We appreciate the contact!
